name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up deno
      uses: denolib/setup-deno@master
      with:
        deno-version: v1.0.0

    - name: Run tests
      run: deno test
